config/routes.rb
Rails.application.routes.draw do

  resources :blogs
  root 'blogs#index'

end

app/models/blog.rb
class Blog < ActiveRecord::Base
  has_attached_file :image, :styles => { :small => "100x100#", :large => "500x500>" }, :default_url => "/images/:style/missing.png", :processors => [:cropper]
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
  attr_accessor :crop_x, :crop_y, :crop_w, :crop_h
  after_update :reprocess_avatar, :if => :cropping?

  def cropping?
    !crop_x.blank? && !crop_y.blank? && !crop_w.blank? && !crop_h.blank?
  end

  def reprocess_avatar
    image.assign(image)
    image.save
  end

  def avatar_geometry(style = :original)
    @geometry ||= {}
    @geometry[style] ||= Paperclip::Geometry.from_file(image.path(style))
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]

  # GET /blogs
  # GET /blogs.json
  def index
    @blogs = Blog.all
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params)
      if @blog.save
        if params[:blog][:image].blank?
          redirect_to @blog, notice: 'Blog was successfully created.'
        else
          render "cropper"
        end
      else
        render :new
      end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    if @blog.update(blog_params)
      if params[:blog][:image].blank?
        redirect_to @blog, notice: 'Blog was successfully updated.'
      else
        render "cropper"
      end
    else
      format.html { render :edit }
      format.json { render json: @blog.errors, status: :unprocessable_entity }
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_params
      params.require(:blog).permit(:title, :description, :image, :crop_x, :crop_y, :crop_w, :crop_h)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/_cropper.html.erb
<div id="layer_content">


   
    <div id="body"><div class="widther">


<div id="jwc_demos">
  <div class="jwc_con_right">
    <img class="jwc_demo2" src="<%= @blog.image.url(:large)%>" alt="jWindowCrop Demo" data-target="#jwc_r2" />
  </div>
</div>

<div id="jwc_demos_result">
  <span id="jwc_r2"></span>
</div>


<%= form_for @blog do |form| %>
  <% for attribute in [:crop_x, :crop_y, :crop_w, :crop_h] %>
    <%= form.text_field attribute, :id => attribute %>
  <% end %>
  <p><%= form.submit "Crop" %></p>
<% end %>


    </div></div>


        

  </div>
  

app/views/blogs/_form.html.erb
<%= form_for(@blog, remote: true, multipart: true) do |f| %>
  <% if @blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
      <% @blog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.file_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
<div id="cropperimageformid"></div>

app/views/blogs/create.js.erb
$("#cropperimageformid").html("<%= escape_javascript(render 'cropper')%>");


  $(function() {
    $('.jwc_demo2').jWindowCrop({
      targetWidth: 660, targetHeight: 120,
      onChange: updateCoords
    });
  });

  function updateCoords(data) {
    var ratio = <%= @blog.avatar_geometry(:original).width %> / <%= @blog.avatar_geometry(:large).width %>;
    $('#crop_x').val(Math.floor(data.cropX * ratio));
    $('#crop_y').val(Math.floor(data.cropY * ratio));
    $('#crop_w').val(Math.floor(data.cropW * ratio));
    $('#crop_h').val(Math.floor(data.cropH * ratio));
  
    //var result_target = $(this).data('target');
    //var results = "x:"+data.cropX + " y:"+data.cropY + " w:"+data.cropW + " h:"+data.cropH;
    //$(result_target).text(results);
  }
  

app/views/blogs/cropper.html.erb
<div id="layer_content">


   
    <div id="body"><div class="widther">


<div id="jwc_demos">
  <div class="jwc_con_right">
    <img class="jwc_demo2" src="<%= @blog.image.url(:large)%>" alt="jWindowCrop Demo" data-target="#jwc_r2" />
  </div>
</div>

<div id="jwc_demos_result">
  <span id="jwc_r2"></span>
</div>


<%= form_for @blog do |form| %>
  <% for attribute in [:crop_x, :crop_y, :crop_w, :crop_h] %>
    <%= form.text_field attribute, :id => attribute %>
  <% end %>
  <p><%= form.submit "Crop" %></p>
<% end %>


<script>
  $(function() {
    $('.jwc_demo2').jWindowCrop({
      targetWidth: 660, targetHeight: 120,
      onChange: updateCoords
    });
  });

  function updateCoords(data) {
    var ratio = <%= @blog.avatar_geometry(:original).width %> / <%= @blog.avatar_geometry(:large).width %>;
    $('#crop_x').val(Math.floor(data.cropX * ratio));
    $('#crop_y').val(Math.floor(data.cropY * ratio));
    $('#crop_w').val(Math.floor(data.cropW * ratio));
    $('#crop_h').val(Math.floor(data.cropH * ratio));
  
    //var result_target = $(this).data('target');
    //var results = "x:"+data.cropX + " y:"+data.cropY + " w:"+data.cropW + " h:"+data.cropH;
    //$(result_target).text(results);
  }
</script>


    </div></div>


        

  </div>

app/views/blogs/edit.html.erb
<h1>Editing blog</h1>

<%= render 'form' %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blogs_path %>

app/views/blogs/index.html.erb
<h1>Listing blogs</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @blogs.each do |blog| %>
      <tr>
        <td><%= blog.title %></td>
        <td><%= blog.description %></td>
        <td><%= link_to 'Show', blog %></td>
        <td><%= link_to 'Edit', edit_blog_path(blog) %></td>
        <td><%= link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Blog', new_blog_path %>

app/views/blogs/new.html.erb
<h1>New blog</h1>

<%= render 'form' %>

<%= link_to 'Back', blogs_path %>

app/views/blogs/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_blog_path(@blog) %> |
<%= link_to 'Back', blogs_path %>

<p>
  <strong>Title:</strong>
  <%= @blog.title %>
</p>
<p>
  <strong>Description:</strong>
  <%= @blog.description %>
</p>
<!-- Show image versions -->
<p>
  <%= image_tag @blog.image.url(:small) %>
</p>
<p>
  <%= image_tag @blog.image.url(:large) %>
</p>
<p>
  <%= image_tag @blog.image.url(:original) %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ImageCrop</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

<%= console %>

</body>
</html>